### ISSUE TITLE
Add Notifications and Push

### ISSUE THREAD

**Issue by mateus-f-torres** [mateus-f-torres/barefoot#218]
### Description
Show more usage of **service-workers** by adding notifications.  
Try adding a **push** for 3 notifications (1min, 1h and 1d).

### Tasks
- [ ] Add a `<button/>` to request permission
- [ ] After permission granted trigger a notifications immediately
- [ ] Setup push system so notifications are triggered by backend server
- [ ] Schedule 3 notifications (1min, 1h and 1d)

**Comment by mateus-f-torres** [comment]
Checkout https://developers.google.com/web/tools/workbox/guides/common-recipes

**Comment by mateus-f-torres** [comment]
### Services

- https://firebase.google.com/docs/cloud-messaging/  
- https://onesignal.com/  
- https://pusher.com/
