### ISSUE TITLE
Change to yarn for package management

### ISSUE THREAD

**Issue by mateus-f-torres** [mateus-f-torres/barefoot#66]
### Description
Although **Barefoot** is a starting point, using `yarn` seems better.  
Almost all other project extended from this template use `yarn` for package management.

### Tasks
- [x] install Yarn v2 (https://yarnpkg.com/getting-started/install)
- [x] remove `package-lock.json`
- [x] run `yarn install`
- [x] fix whatever problems may arise
    - like **webpack v4** and the need for https://github.com/arcanis/pnp-webpack-plugin

**Comment by mateus-f-torres** [comment]
### Resources
https://yarnpkg.com/advanced/qa#which-files-should-be-gitignored  
https://yarnpkg.com/features/zero-installs

**Comment by mateus-f-torres** [comment]
### Note
It might be the time to experiment with `webpack@5` again  
Most of the used plugins have released patches for compatibility

**Comment by mateus-f-torres** [comment]
### Note
At the moment there are some compatibility issues with **cypress v5** and **yarn v2**  
The related issues are described in the commit messages for #72  

The main workaround was using **nodeLinker** to return default `node_modules` folder  
https://yarnpkg.com/advanced/migration#if-required-enable-the-node-modules-plugin
