### ISSUE TITLE
Analyze need for Travis CI

### ISSUE THREAD

**Issue by mateus-f-torres** [mateus-f-torres/barefoot#74]
### Description
See if there really is a need and a gain from using a service like **Travis CI** here.  
[Github Actions](https://docs.github.com/en/actions) and [Netlify Build Plugins](https://docs.netlify.com/configure-builds/build-plugins/) could be a better fit.

### Tasks
- [ ] Dive deep into why one would use **Travis CI**
- [ ] Study **Github Actions**
- [ ] Study **Netlify Build Plugins**

**Comment by mateus-f-torres** [comment]
As this project is quite simple there is no need for a full **CI** tool like **Travis CI** or **Circle CI**  
We need only run the `build` and `test` scripts and that is that.

Invest in **Github Actions** and **Netlify**
