### ISSUE TITLE
Try Docker

### ISSUE THREAD

**Issue by mateus-f-torres** [mateus-f-torres/barefoot#94]
### Description
Setup a example `Dockerfile` for a template front-end  
Might be nice to combine with `docker-compose` and `puppeteer`

### Tasks
- [x] setup basic `yarn start` Dockerfile 1st
- [x] setup basic `yarn build`, then **nginx** serve 2nd
- [x] reduce docker image size
